# Generated by Django 4.1.7 on 2023-04-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tutorname', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback12', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
